### ISSUE TITLE
Adjust data access layer in OrdersService (replace EF Core, introduce database)

### ISSUE THREAD

**Issue by feO2x** [thinktecture-labs/cloud-native-sample#119]
Entity Framework Core has shown several performance problems, especially when a web service in a Kubernetes cluster receives its first request. Additionally, the orders are currently not persisted, but only saved to the volatile in-memory database of EF Core.

The following changes should be made:

1. Replace EF Core with another technology (Which one? Simple ADO.NET? Or a Micro-ORM like [LinqToDB](https://github.com/linq2db/linq2db)?
2. Introduce a database for the orders service (which one? The project currently references `Microsoft.EntityFrameworkCore.SqlServer` and `Microsoft.EntityFrameworkCore.Sqlite`, but shouldn't we use something like PostgreSQL or MariaDB?)
3. Introduce a simple migration mechanism that sets up the database during deployment / on first run.
4. Adjust the `docker-compose.yml` file to include a service with the new database for the OrdersService
5. Adjust the Terraform project to include the database for the OrdersService (I guess we want to rent?)

**Comment by feO2x** [comment]
@ThorstenHans could you please clarify the open questions on this task when you have time for it?

**Comment by ThorstenHans** [comment]
As discussed in our call, we should change the OrdersService to address persistence as described below:

- [ ] provision a SQL Azure database using Terraform (as we do for ProductService)
- [ ] stick with EF Core for addressing persistence concerns
- [ ] if OrdersService is started without a connection string, the service should fallback to in-memory "persistence". (Similar to the behavior of the ProductsService to simplify local execution)
- [ ] Helm Chart for OrdersService should be updated to use RollingUpgrade as `deploymentStrategy` (see note below)


We have to alter the deployment strategy of OrdersService in `/charts/orders/templates/deployment.yaml`  to ensure that existing OrdersService deployments will be terminated before a new version of OrdersService will be deployed. This allows frictionless execution of migrations during application startup. By leveraging `maxSurge: 1` and `maxUnavailable: 0` we can ensure that only one replica of OrderService in a version is started at a single point in time. Once the API becomes `ready` (meaning that Kubernetes was able to invoke the `/heathz/readiness` endpoint, the next replica is started. This is quite important because EF Core is not as "cloud-native" as it should be 😄 

```yaml
type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```
